set.seed(853)
simulated_data <-
  tibble( 
    state_code = sample(x=c(1,
                            2,
                            4,
                            5,
                            6,
                            8,
                            9,
                            10,
                            11,
                            12,
                            13,
                            15,
                            16,
                            17,
                            18,
                            19,
                            20,
                            21,
                            22,
                            23,
                            24,
                            25,
                            26,
                            27,
                            28,
                            29,
                            30,
                            31,
                            32,
                            33,
                            34,
                            35,
                            36,
                            37,
                            38,
                            39,
                            40,
                            41,
                            42,
                            44,
                            45,
                            46,
                            47,
                            48,
                            49,
                            50,
                            51,
                            53,
                            54,
                            55,
                            56
    ), 3300000,replace = TRUE),
    BMI = 
      runif(n = 3300000,
            min = 18.5, 
            max = 186),
    sleeping =  sample(x=0:24, 3300000,replace = TRUE),
    health =  sample(x=1:5, 3300000,replace = TRUE),
    sex =  sample(x=0:1, 3300000,replace = TRUE),
    smoke =  sample(x=0:1, 3300000,replace = TRUE),
    age =  sample(x=18:100, 3300000,replace = TRUE),
    exercise =  sample(x=0:1, 3300000,replace = TRUE),
    alcohol =  sample(x=0:1, 3300000,replace = TRUE)
  )
head(simulated_data) %>% 
  kable(caption = "summary statistic of Body Mass Index") %>%
  kable_classic(full_width = F, html_font = "Cambria") %>%
  kable_styling(latex_options = "HOLD_position")